# Makefile for the SPC-700 textbook PDF build.
# Convenience wrapper around build.sh + a clean target.

.PHONY: build clean

build:
	./build.sh

clean:
	rm -f spc700_textbook_processed.md
	rm -f *.aux *.log *.toc *.out
